name: Build with Conditional Security Scans

on:
  push:
    branches:
      - main

jobs:
  ###################################################################
  # 1) BUILD JOB
  ###################################################################
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t fafiorim/firefly:latest .

      - name: Save Docker image
        run: docker save fafiorim/firefly:latest -o firefly.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: firefly.tar

  ###################################################################
  # 2) SECURITY SCAN
  ###################################################################
  security-scan:
    if: ${{ vars.SECURITY_ENABLED != 'false' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Docker artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Install Artifact Scan CLI
        run: ./tmas_install.sh

      - name: Set TMAS_API_KEY
        run: echo "TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      - name: Run Full Security Scan
        run: tmas scan docker-archive:firefly.tar -VMS --saveSBOM > scan-results.json

      - name: Debug - Check if scan-results.json Exists
        run: ls -l scan-results.json

      - name: Upload Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: scan-results.json

  ###################################################################
  # 3) PARSE SCAN RESULTS
  ###################################################################
  parse-scan-results:
    if: ${{ vars.SECURITY_ENABLED != 'false' }}
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Download Scan Results
        uses: actions/download-artifact@v3
        with:
          name: scan-results
          path: .

      - name: Debug - Check Scan Results File
        run: ls -l scan-results.json

      - name: Parse Vulnerabilities
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          jq '{ vulnerabilities: .vulnerabilities }' scan-results.json > vulnerability-scan-results.json

      - name: Parse Malware
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          jq '{ malware: .malware }' scan-results.json > malware-scan-results.json

      - name: Parse Secrets
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          jq '{ secrets: .secrets }' scan-results.json > secret-scan-results.json

  ###################################################################
  # 4) UPLOAD VULNERABILITY SCAN RESULTS
  ###################################################################
  upload-vulnerability-results:
    needs: parse-scan-results
    runs-on: ubuntu-latest
    steps:
      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: vulnerability-scan-results
          path: vulnerability-scan-results.json

  ###################################################################
  # 5) UPLOAD MALWARE SCAN RESULTS
  ###################################################################
  upload-malware-results:
    needs: parse-scan-results
    runs-on: ubuntu-latest
    steps:
      - name: Upload Malware Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: malware-scan-results
          path: malware-scan-results.json

  ###################################################################
  # 6) UPLOAD SECRETS SCAN RESULTS
  ###################################################################
  upload-secrets-results:
    needs: parse-scan-results
    runs-on: ubuntu-latest
    steps:
      - name: Upload Secrets Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: secrets-scan-results
          path: secret-scan-results.json

  ###################################################################
  # 7) UPLOAD SBOM
  ###################################################################
  upload-sbom:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Upload SBOM Results
        uses: actions/upload-artifact@v3
        with:
          name: sbom-report
          path: SBOM_*.json

  ###################################################################
  # 8) PUSH IMAGE
  ###################################################################
  push-image:
    needs:
      - upload-vulnerability-results
      - upload-malware-results
      - upload-secrets-results
      - upload-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Docker artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load --input firefly.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push fafiorim/firefly:latest
